<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Yarp" />
    <ProjectReference Include="..\CommunityHub.Web.Client\CommunityHub.Web.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunityHub.ServiceDefaults\CommunityHub.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>